---
sidebar: sidebar 
permalink: ONTAP/choose-ontap-910-later.html 
keywords: choose ontap target version, ontap update recommendations, identify ontap target version, recommended version, benefits and risks or ONTAP version 
summary: ONTAP 스토리지 시스템을 업그레이드하기 전에 각 ONTAP 버전의 이점과 위험을 이해하세요. 
---
= 소프트웨어 업데이트 사용의 이점과 위험을 이해하기 위해 ONTAP 버전을 비교하세요.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
스토리지 시스템에 대한 ONTAP 버전을 업데이트하기 전에 ONTAP 대상 버전과 관련된 이점과 위험을 비교하고 이해하는 것이 매우 중요합니다.

ONTAP 에서 특정 버전으로 업데이트하는 이점을 파악하기 위해 대상 버전을 선택하고 현재 버전과 비교할 수 있습니다.  또한 ONTAP 의 특정 버전으로 업데이트하면 해결될 위험과 발생할 수 있는 새로운 위험(있는 경우)도 확인할 수 있습니다.


NOTE: ONTAP 9.10 이상 버전을 사용하는 경우에만 이 기능을 사용할 수 있습니다.

.단계
. 콘솔 왼쪽 탐색에서 *상태* > *소프트웨어 업데이트*를 선택합니다.
+
소프트웨어 업데이트가 필요한 클러스터 목록이 표시됩니다.  권장 대상 버전으로 업데이트하거나 다른 버전을 선택할 수 있습니다.



|===
| 만약 당신이... | 이렇게 하세요... 


 a| 
추천 버전으로 업데이트하고 싶습니다
 a| 
. *대상 버전* 열에서 *버전 비교*를 클릭하면 권장 ONTAP 버전으로 업데이트할 경우의 기능적 이점과 위험 이점을 확인할 수 있습니다.
. 업데이트 후 해결될 위험, 계속 존재할 위험, 새로 발생할 위험에 대한 정보를 선택하고 확인하세요.
. 선택적으로 *업데이트 계획 다운로드*를 클릭하여 업데이트 계획 사본을 다운로드합니다.
. 업데이트 프로세스를 시작하려면 *업데이트 시작*을 클릭하세요.




 a| 
다른 버전을 선택하고 싶습니다
 a| 
. *대상 버전* 열에서 드롭다운을 클릭하고 *다른 버전 선택*을 선택합니다.
. 버전을 선택하여 기능상의 이점과 위험 이점을 확인하세요.
. 업데이트 후 해결될 위험, 계속 존재할 위험, 새로 발생할 위험에 대한 정보를 선택하고 확인하세요.
. 선택적으로 *업데이트 계획 다운로드*를 클릭하여 업데이트 계획 사본을 다운로드합니다.
. 업데이트 프로세스를 시작하려면 *업데이트 시작*을 선택하세요.


|===