---
sidebar: sidebar 
permalink: get-started/software-updates-faq.html 
keywords: ontap update faq, ontap update frequently asked questions, software updates faq, software updates frequently asked questions, troubleshooting 
summary: 소프트웨어 업데이트에 대한 자주 묻는 질문에 대한 답변을 확인하세요. 
---
= 소프트웨어 업데이트에 대한 자주 묻는 질문
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
소프트웨어 업데이트에 대해 자세히 알고 싶거나 문제 해결에 도움이 필요한 경우, 이러한 질문을 검토하면 빠르게 답변을 얻을 수 있습니다.

*소프트웨어 업데이트 URL은 무엇인가요?*

브라우저에서 URL을 입력하세요. https://console.netapp.com/["https://console.netapp.com/"^] NetApp Console 액세스하려면.

*소프트웨어 업데이트를 사용하려면 라이선스가 필요합니까?*

NetApp 라이선스 파일(NLF)은 필요하지 않습니다.

*클러스터의 ONTAP 버전을 업데이트한 후에도 기록 탭에서 클러스터를 볼 수 없는 이유는 무엇입니까?*

클러스터가 기록 탭에 나타나기까지 2~3시간이 걸립니다.  클러스터의 ONTAP 버전이 업데이트되면 AutoSupport 생성됩니다.  AutoSupport 데이터를 처리하고 ONTAP 의 최신 버전을 반영하는 데 2~3시간이 걸립니다.

*클러스터의 ONTAP 버전을 업데이트한 후에도 소프트웨어 업데이트 대시보드에 이전 버전의 ONTAP 이 표시되는 이유는 무엇입니까?*

클러스터가 기록 탭에 나타나기까지 2~3시간이 걸립니다.  클러스터의 ONTAP 버전이 업데이트되면 AutoSupport 생성됩니다.  AutoSupport 데이터를 처리하고 ONTAP 의 최신 버전을 반영하는 데 2~3시간이 걸립니다.

*업데이트에 따라 다른 화면이 표시되는 이유는 무엇인가요?*

이는 현재 ONTAP 버전과 클러스터용 콘솔 에이전트를 사용할 수 없기 때문입니다.  콘솔 에이전트는 콘솔 내에서 ONTAP 업데이트를 수행하므로 업데이트를 위해 콘솔 밖으로 나갈 필요가 없습니다.  콘솔 에이전트가 없으면 시스템 관리자로 리디렉션되며 ONTAP 클러스터 자격 증명을 다시 입력해야 합니다.  ONTAP 의 다양한 버전에 대한 ONTAP 업데이트 프로세스에 대한 정보는 다음을 참조하세요.link:https://docs.netapp.com/us-en/bluexp-software-updates/get-started/software-updates.html["지원되는 ONTAP 시스템"] .

*클러스터를 발견하려면 무엇이 필요한가요?*

원하는 클러스터에 대한 ONTAP 업데이트를 수행하려면 ONTAP 클러스터 IP와 클러스터에 연결하기 위한 관리자 자격 증명이 필요합니다.  클러스터 검색의 일부로 ONTAP 업데이트가 자동으로 실행될 수 있도록 이러한 세부 정보를 제공해야 합니다.

또한 다음 액세스 역할 중 하나가 필요합니다: 조직 관리자, 폴더 또는 프로젝트 관리자, 저장소 관리자.
