---
sidebar: sidebar 
permalink: get-started/software-updates.html 
keywords: ontap 9.10.1, ontap update, supported systems for ontap update, ontap version, software updates benefits 
summary: 소프트웨어 업데이트를 사용하여 새롭고 향상된 기능을 활용하고 ONTAP 스토리지 시스템을 원활하게 업데이트하세요. 
---
= 소프트웨어 업데이트에 대해 알아보세요
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
소프트웨어 업데이트를 사용하면 고객이 ONTAP 업데이트를 간소화할 수 있습니다.  이를 통해 비용을 절감하고, 중요한 작업 부하를 가속화하고, 보안을 강화할 수 있습니다.

소프트웨어 업데이트는 평가, 계획 및 실행 프로세스를 자동화합니다.  지능형 업그레이드 어드바이저는 특정 시스템에 가장 적합한 버전을 예측하고, 문제를 해결할 수 있는 버전을 추천하며, 효율성을 개선하고 시스템 보안을 강화하여 고객이 자신의 요구 사항에 가장 적합한 옵션을 결정할 수 있도록 해줍니다.  그런 다음 소프트웨어 패키지를 배포하고 지원 서비스와는 별도로 자동 비배포 업그레이드(ANDU)를 자동으로 실행합니다.



== NetApp Console

소프트웨어 업데이트는 NetApp Console 통해 접근할 수 있습니다.

NetApp Console 엔터프라이즈급 온프레미스 및 클라우드 환경 전반에서 NetApp 스토리지 및 데이터 서비스를 중앙에서 관리할 수 있는 기능을 제공합니다. NetApp 데이터 서비스에 액세스하고 사용하려면 콘솔이 필요합니다. 관리 인터페이스로서, 하나의 인터페이스에서 여러 스토리지 리소스를 관리할 수 있습니다. 콘솔 관리자는 기업 내 모든 시스템의 저장소와 서비스에 대한 액세스를 제어할 수 있습니다.

NetApp Console 사용하려면 라이선스나 구독이 필요하지 않으며, 스토리지 시스템이나 NetApp 데이터 서비스에 대한 연결을 보장하기 위해 클라우드에 Console 에이전트를 배포해야 할 때만 요금이 부과됩니다. 그러나 콘솔에서 액세스할 수 있는 일부 NetApp 데이터 서비스는 라이선스 기반이거나 구독 기반입니다.

자세히 알아보세요 https://docs.netapp.com/us-en/bluexp-setup-admin/concept-overview.html["NetApp Console"] .



== 지원되는 ONTAP 시스템

ONTAP 9.10.1 이상 버전을 사용 중인 경우에만 소프트웨어 업데이트를 통해 ONTAP 업데이트를 완료할 수 있습니다.

다음 정보는 다양한 ONTAP 버전에 대한 소프트웨어 업데이트 프로세스를 제공합니다.

|===
| *현재 ONTAP 버전* | *업데이트 프로세스* 


| 9.12.1 이상 | ONTAP 업데이트의 모든 단계는 콘솔 내에서 진행됩니다. 


| 9.10.1 ~ 9.12.1 | ONTAP 업데이트 준비는 소프트웨어 업데이트 화면에서 진행됩니다.  실제 ONTAP 업데이트를 수행하려면 시스템 관리자로 이동해야 합니다.  콘솔 내에서 ONTAP 업데이트의 모든 단계를 실행하려면 다음이 필요합니다.link:https://docs.netapp.com/us-en/bluexp-setup-admin/task-install-connector-on-prem.html["콘솔 에이전트 설정"] . 


| 9.8에서 9.10.1까지 | ONTAP 업데이트 준비는 소프트웨어 업데이트 화면에서 진행됩니다.  실제 ONTAP 업데이트를 수행하려면 시스템 관리자로 이동해야 합니다. 
|===

NOTE: Cloud Volumes ONTAP에서는 소프트웨어 업데이트가 지원되지 않습니다.



== 소프트웨어 업데이트 사용의 이점

ONTAP 스토리지 시스템을 업데이트하면 스토리지 시스템의 성능, 보안 및 기능을 개선하는 데 도움이 됩니다.

ONTAP 스토리지 시스템을 업데이트하면 다음과 같은 이점이 있습니다.

* 새로운 프로토콜, 데이터 서비스, 클라우드 통합 옵션 등 ONTAP 제공하는 최신 기능과 향상된 기능에 액세스할 수 있습니다.
* 시스템의 안정성, 신뢰성 또는 보안에 영향을 미칠 수 있는 버그나 취약점을 수정할 수 있습니다.
* 최신 패치와 개선 사항을 적용하면 시스템 성능과 효율성을 최적화할 수 있습니다.
* 다른 NetApp 제품, 타사 애플리케이션 및 클라우드 공급자와의 호환성과 상호 운용성을 보장할 수 있습니다.
* NetApp 최신 ONTAP OS 버전에 대해 제공하는 지속적인 지원과 유지관리의 혜택을 누릴 수 있습니다.




== 비용

NetApp 소프트웨어 업데이트 사용에 대해 요금을 청구하지 않습니다.
