---
sidebar: sidebar 
permalink: release-notes/whats-new.html 
keywords: 'software updates, ontap update, what"s new, enhancements' 
summary: 소프트웨어 업데이트에 도입된 새로운 기능과 향상된 기능에 대해 알아보세요. 
---
= 소프트웨어 업데이트의 새로운 기능
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
소프트웨어 업데이트의 새로운 내용을 알아보세요.



== 2025년 10월 6일



=== BlueXP software updates 이제 소프트웨어 업데이트입니다.

BlueXP software updates 소프트웨어 업데이트로 이름이 바뀌었습니다.

NetApp 콘솔 왼쪽 탐색 모음에서 *상태* > *소프트웨어 업데이트*를 선택하여 액세스할 수 있습니다.



=== BlueXP 는 이제 NetApp 콘솔입니다.

강화되고 재구성된 BlueXP 기반을 기반으로 구축된 NetApp 콘솔은 엔터프라이즈급 온프레미스 및 클라우드 환경 전반에서 NetApp 스토리지와 NetApp 데이터 서비스를 중앙에서 관리하여 실시간 통찰력, 더 빠른 워크플로, 간소화된 관리를 제공하며, 높은 보안성과 규정 준수를 보장합니다.

변경된 내용에 대한 자세한 내용은 다음을 참조하세요. https://docs.netapp.com/us-en/bluexp-relnotes/index.html["NetApp 콘솔 릴리스 노트"] .



== 2025년 5월 12일



=== BlueXP 액세스 역할이 필요합니다

이제 소프트웨어 업데이트를 설치하려면 다음 액세스 역할 중 하나가 필요합니다. *조직 관리자*, *폴더 또는 프로젝트 관리자*, *저장소 관리자*, *저장소 뷰어* 또는 *저장소 상태 전문가*.  저장소 뷰어 역할이 있는 사용자는 소프트웨어 업데이트와 관련된 다양한 권한을 가지고 있지만, 소프트웨어 업데이트를 설치할 수는 없습니다.link:https://docs.netapp.com/us-en/bluexp-setup-admin/reference-iam-predefined-roles.html["BlueXP 액세스 역할에 대해 알아보세요."^]



== 2025년 4월 2일



=== 완화된 위험

BlueXP software updates 의 요약 섹션에서 이제 운영 체제 업데이트로 완화할 수 있는 위험의 총 수를 볼 수 있습니다.  이를 통해 사용자는 설치 기반의 보안 및 안정성 개선 사항을 평가할 수 있습니다.



== 2024년 8월 7일



=== ONTAP 업데이트

BlueXP software updates 서비스는 위험을 완화하고 고객이 ONTAP 기능을 최대한 활용할 수 있도록 보장함으로써 사용자에게 원활한 업데이트 환경을 제공합니다.

자세히 알아보세요 link:https://docs.netapp.com/us-en/bluexp-software-updates/get-started/software-updates.html["BlueXP software updates"] .
